@extends('layouts.web-main')
@section('main-container')
<div class="innerpage-banner" id="home" style="background: url({{url('/')}}/dist/assets/img/bread/breadcrumbs.jpg) no-repeat center; background-size: cover;">
    <div class="inner-page-layer">
        <h5>Privacy Policy</h5>
        <h6><a href="{{url('/')}}">Home</a>&nbsp;/&nbsp;<span>Privacy Policy</span></h6>
    </div>
</div>

<section class="ptb--30" style="background: #f5f5f5">
    <div class="container">
        <div class="about-content terms_and_condition_content_point dealer_icon">
            <p>Share Digital Card Partnership Firm, Mumbai, the Vendor, through its Website
                <a href="www.sharedigitalcard.com">www.sharedigitalcard.com</a> brings to you its Product, Share Digital Card.
                The Vendor may receive data (inclusive of credentials, content and information
                referred to in the <a href="terms-and-conditions.php">Terms and Conditions</a> and <a href="terms-of-use.php">Terms of Use</a>
                from you during and as a consequence of your access or use of the Website, and your
                Registration, Subscription or Use of the Product, and such data shall be governed by
                this Privacy Policy. The Vendor insists upon your prior perusal and understanding of
                the same, and informs you that your access or use of the Website shall automatically
                signify your consent to be bound by the Privacy Policy, since the same constitutes an
                electronic record defined under the laws prevailing in the Republic of India, and
                having been generated by a computer system does not require physical or
                personalized digital signatures for its authentication and enforcement.</p>

            <h5><b>Need for collection</b></h5>

            <p>The Vendor needs to collect data from you for better understanding of your
                requirements; providing you with consistently improving services; maintaining,
                enhancing and adding to the features availed by you; ensuring your valid
                identification, authentication and security; keeping and maintaining of your records;
                and communicating to you its support and information as per your requirements and
                interests.
            </p>

            <h5><b>Mode of Collection</b></h5>

            <p>The Vendor may receive your data through following modes:</p>

            <p><b>Direct collection</b></p>

            <div class="p-left-20 dealer_icon">
                <p><i class="fa fa-angle-right"></i>  For and through Registration – including but not limited to your personal
                    information like name, Email Id, physical address, phone number, etc.
                </p><p><i class="fa fa-angle-right"></i>  For and through Subscription – including but not limited to information
                    required for verification of your identity like details of your Aadhar Card,
                    PAN Card, etc.; banking information required for making payment(s); your
                    expression of interest in the Features of the Product, etc.
                </p><p><i class="fa fa-angle-right"></i>  For and through use – including but not limited to your personal and
                    professional information that you may customize into the Product (apart from
                    the information shared for Registration) like your designation(s),
                    photograph(s), logo(s), official address, details of your employer / employees /
                    team, services, clients, links to your social media account(s), third party
                    information, etc.; your proclivity in use of the Product; your insight upon its
                    Features, etc.
                </p><p><i class="fa fa-angle-right"></i>  For and through communications – including but not limited to your Email,
                    postal or telephonic conversations, like your queries, discussions, requests for
                    services, etc.
                </p><p><i class="fa fa-angle-right"></i>  By linking to social media – including but not limited to your linking of the
                    Vendor, its Website or its Product to your social media Account(s) and
                    granting access to your information contained therein, as the case may be, to
                    the Vendor.</p>
            </div>
            <p><b>Automated collection</b></p>
            <div class="p-left-20 dealer_icon">
                <p><i class="fa fa-angle-right"></i> Browsing information – including but not limited to your Internet Protocol
                    (IP) Address, Internet Service Provider (ISP), Web Browser, Operating
                    System, Date and Time Stamp, Geolocation, etc.
                </p><p><i class="fa fa-angle-right"></i>  Analytical information – including but not limited to your clickstream patterns
                    and paths, heatmaps, etc.
                </p><p><i class="fa fa-angle-right"></i>  Statistical information – including but not limited to your use, interaction and
                    preferences with the Website, Product and services offered by the Vendor,</p>
                <p><b>Indirect collection</b></p>
                <p><i class="fa fa-angle-right"></i> Information received consequential to your access or use of the Website, and your
                    Registration, Subscription or Use of the Product, from sources other than the ones
                    mentioned hereinabove, but linked to your transaction(s) with the Vendor, its
                    Website, Product and / or services.</p>
            </div>
            <h5><b>Storage of data</b></h5>
            <p>Physical storage – The data received by the Vendor shall be physically stored in a
                secured Server installed and maintained at the headquarters of Vendor being</p>
            <p>Virtual storage – The data received by the Vendor shall be virtually stored in Log
                files and Cookies.</p>
            <div class="p-left-20 dealer_icon">
                <p>Explanation:<br><i class="fa fa-angle-right"></i> Log files and Cookies are brief records of your information stored on the hard
                    drive for purposes of enabling, easing and improving your access or use of the
                    Website, and your Registration, Subscription or Use of the Product.
                </p><p><i class="fa fa-angle-right"></i>  Such records may be strictly necessary without which desired services cannot
                    be availed; or may be partially necessary to assess your performance and to
                    enable tailoring of such services to suit your needs; or may be optional to
                    introduce you with advertisement campaigns related to your interests.
                </p><p><i class="fa fa-angle-right"></i>  You have the liberty to enable or disable creation, maintenance and accessing
                    of such records by the Vendor through respective settings of your equipment
                    and facilities utilized for access or use of the Website, and Registration,
                    Subscription or Use of the Product.
                </p>
            </div>


            <h5><b>Protection of data</b></h5>

            <p>The Vendor maintains physical, electronic and procedural safeguards with respect to
                data received from you in compliance of the laws prevailing in the Republic of India,
                and ensures encryption of the information that may be deemed by it to be sensitive
            </p>
            <h5><b>Sharing of data</b></h5>

            <p>The Vendor may disclose the data received from you in the following ways:</p>
            <p>With its affiliates, employees, agents, contractors and service-providers;

            </p>
            <div class="p-left-20 dealer_icon">
            <p><i class="fa fa-angle-right"></i>  With third-parties indispensable from the process of services of the Vendor;
            </p><p><i class="fa fa-angle-right"></i>  With public as testimonials, endorsements and promotions;
            </p><p><i class="fa fa-angle-right"></i>  With its professional consultants like Accountants, Lawyers, etc.;
            </p><p><i class="fa fa-angle-right"></i>  With law enforcement, investigatory and adjudicatory bodies; and,
            </p><p><i class="fa fa-angle-right"></i>  As may be required by the laws prevailing in the Republic of India.
            </p>
            </div>
            <h5><b>Confidentiality of data</b></h5>

            <p>Except as provided hereinabove, the Vendor otherwise undertakes to maintain
                confidentiality of your data (or part thereof) that you inform the Vendor to be
                confidential in nature, with the same degree and care as it would deploy to protect its
                own Confidential Information.</p>
            <h5><b>Non-ownership of data</b></h5>

            <p>The Vendor claims no ownership upon your data or upon the data of any third
                party(ies).</p>
            <h5><b>Retention of data</b></h5>

            <p>The Vendor shall however be required to retain your data with itself during and until
                you continue to avail its Services, or longer if so required for facilitating, recordkeeping, accounting, investigating and / or legal purposes, as may be deemed fit by
                the Vendor.</p>
            <h5><b>Discretion</b></h5>

            <p>The Vendor may, at its sole discretion, alter, remove, restrict, suspend or terminate its
                method / policy of mode of collection, storage, protection, sharing and / or retention
                of data, or may amend and enforce amendment(s) of the Privacy Policy as it may
                deem fit, without any prior notice to you; and it shall be your responsibility to keep
                yourself conversant with the same to ensure your pragmatic compliance of the
                Privacy Policy.</p>
            <h5><b>Disclaimer</b></h5>

            <p>The Vendor shall not, under any circumstances, assume, ratify or defend your
                ownership upon the data received from you, or its accuracy, authenticity,
                correctness, validity and legality.
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to your lack of diligence, vigilance or prudence in protecting
                your data and / or your sharing of credentials of your Account / Subscription with
                any third party(ies).
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to your sharing of the same with any third party(ies), and
                although the same may be consequential to services of the Vendor, such data shall
                be governed by respective Privacy Policy(ies) of such third party(ies).
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to unauthorized and / or unlawful use of your Account,
                Subscription and / or Share Digital Card.
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to causes beyond its control including but not limited to
                maintenance, power failure, server malfunction, content loss, misuse or abuse,
                unwarranted access gained by hackers, viruses or like infiltrators, force majeure,
                etc.
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to human error and error of belief, opinion or judgment.
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused due to your equipment or facilities utilized for access or use of the
                Website, or Registration, Subscription or Use of the Product.
            </p><p>The Vendor shall not be liable for any loss(es) of your data or any consequential
                loss(es) caused as a consequence of any action or omission at the behest of any
                person, entity or bot representing the Vendor without due authorization from the
                Vendor.
            </p><p>The Vendor shall not represent, ratify or defend you in any claim or complaint
                made against you in pursuance of your data owing to any action or omission on
                your part during, out of the course of, or in consequence of access or use of the
                Website; Registration, Subscription or Use of the Product; and / or in violation of
                the Privacy Policy.</p>
            <h5><b>Liability and Indemnification</b></h5>

            <p>You shall solely be liable for, and shall indemnify, defend and hold the Vendor
                harmless for any loss(es) caused to data belonging to you, to any third party(ies), or to
                the Vendor; or for any consequential loss(es); or for such loss(es) that may be saddled
                upon the Vendor, owing to any action or omission on your part during, out of the
                course of, or in consequence of access or use of the Website; Registration,
                Subscription or Use of the Product; and / or in violation of the Privacy Policy.</p>
            <h5><b>Dispute Redressal</b></h5>

            <p>Any dispute arising out of or in connection with the data transacted for access and / or
                use of the Website; Registration, Subscription or Use of the Product; and / or in
                violation of the Privacy Policy, shall be communicated by the aggrieved party to the
                other party within three (3) days of occurrence of such grievance, upon which the
                parties shall endeavour to resolve the same amicably within subsequent 15 days,
                however, if such dispute is not so resolved, then either party may initiate Arbitration
                proceedings for redressal of such dispute by serving the other party with a Notice of
                15 days to that effect, and the Vendor shall accordingly appoint a sole Arbitrator to
                govern the Arbitral Tribunal at Mumbai, India, as per the Indian Arbitration and
                Conciliation Act, 1996.
            </p>
            <h5><b>Governing Law and Jurisdiction</b></h5>

            <p>The Privacy Policy, and the aforementioned process of dispute redressal shall be
                governed by the laws prevailing in the Republic of India, being subject to the
                jurisdiction for the purposes of enforcement, intervention and execution of the said
                process vested in the Courts at Mumbai, India</p>
            <h5><b>Contact:</b></h5>

            <p>The official contact information of the Vendor for all purposes shall be its Email Id –
                <a href="mailto:info@sharedigitalcard.com">info@sharedigitalcard.com.</a></p>

        </div>
    </div>
</section>

@endsection
