@extends('layouts.web-main')
@section('main-container')
    <div class="innerpage-banner" id="home" style="background: url({{url('/')}}/dist/assets/img/bread/breadcrumbs.jpg) no-repeat center; background-size: cover;">
        <div class="inner-page-layer">
            <h5>Terms of Use</h5>
            <h6><a href="{{url('/')}}">Home</a>&nbsp;/&nbsp;<span>Terms of Use</span></h6>
        </div>
    </div>

    <section class="ptb--30" style="background: #f5f5f5">
        <div class="container">
            <div class="about-content terms_and_condition_content_point dealer_icon">
                <p>Share Digital Card, a digital business card is a Product created, owned and distributed
                    by Share Digital Card Partnership Firm, Mumbai, the Vendor through its Website
                    <a href="www.sharedigitalcard.com">www.sharedigitalcard.com</a>, which shall be governed by these Terms of
                    Use. The Vendor insists upon your prior perusal and understanding of the same, and
                    informs you that your access or use of the Website shall automatically signify your
                    consent to be bound by the Terms of Use, since the same constitutes an electronic
                    record defined under the laws prevailing in the Republic of India, and having been
                    generated by a computer system does not require physical or personalized digital
                    signatures for its authentication and enforcement.


                </p>

                <h5><b>Registration</b></h5>

                <p>
                    The Product can be accessed by creating an Account on the Website by setting up
                    your personal information including your name, Email Id, physical address, phone
                    number, Login Id and password, and upon complying with the primary contactverification process
                </p>
                <p>
                    It shall be deemed to have been undertaken by you that the information provided,
                    belongs to you and is not false, fraudulent or illegal.
                </p>
                <p>It shall solely be your responsibility to protect your Account credentials, and any
                    use, misuse or abuse of your the same shall be attributable to you.</p>
                <p>In the event where any unauthorised access or operation of your Account comes to
                    your knowledge, you shall promptly report the same to the Vendor.</p>
                <p>The Account shall be operated only by the person whose personal information has
                    been entered in the same, and it shall enable the said person to avail only one
                    Product per Account.</p>
                <p>The Vendor reserves its right to refuse your Registration and creation of your
                    Account, at its discretion.</p>

                <h5><b>Subscription</b></h5>

                <p> The Product can be created, modified and used by <a href="pricing.php">subscribing to Plans</a> offered by the Vendor from time to time.</p>
                <!-- <div class="p-left-20 dealer_icon">
                    <p><i class="fa fa-angle-right"></i>  Free Trial: For a period of five (5) days from the date of Registration for the
                        first time, at no cost.
                    </p><p><i class="fa fa-angle-right"></i>  Annual: For a period of one (1) year from the date of Subscription, at a
                        Subscription Fee of Rs. 999/-.
                    </p><p><i class="fa fa-angle-right"></i>  Triennial: For a period of three (3) years from the date of Subscription, at a
                        Subscription Fee of Rs. 1,999/-.
                    </p><p><i class="fa fa-angle-right"></i>  Quinquennial: For a period of five (5) years from the date of Subscription, at a
                        Subscription Fee of Rs. 2,999/-.
                    </p><p><i class="fa fa-angle-right"></i>  Lifetime: For your lifetime from the date of Subscription, at a Subscription
                        Fee of Rs. 4,999/-.
                    </p>

                </div> -->
                <p>The Subscription Fee of opted Plan shall be payable by you at the beginning of
                    Subscription or (in case of) modification / renewal through either of the modes or
                    payment prescribed by the Vendor from time to time.
                </p>
                <p>The Subscription once opted shall be non-transferrable and the Subscription Fee
                    once paid shall be non-refundable, under any circumstances.
                </p>
                <p>The Vendor reserves its right to change the Subscription Fee at any point of time
                    without issuing any prior notice, however, such change shall not affect the
                    existing Subscription (if any) until its expiry.
                </p>
                <p>The Subscription shall be considered valid only through your compliance of the
                    Indian Contract Act, 1872, including your competence in terms of majority of age,
                    soundness of mind, solvency and legality of your Registration, Subscription and /
                    or Use of the Product.
                </p>
                <p>The Subscription shall not survive through and beyond suspension, winding up or
                    dissolution of the Vendor, and / or discontinuation of the Product.
                </p>
                <p>The Vendor reserves its right to refuse your Subscription, at its discretion.</p>


                <h5><b>Features</b></h5>

                <p>
                    <a href="feature.php">The Features </a> of the Product shall remain consistent for all the
                    Subscription Plans, however, the Vendor may change such arrangement, at its
                    discretion.
                </p>
                <p>The Product and / or its Features may be updated, upgraded and / or modified by
                    the Vendor if such need arises to the satisfaction of Vendor, and at its discretion.
                </p>
                <p>The Vendor shall endeavour to acknowledge your requests / suggestions towards
                    updation, upgradation and / or modification of the Product and / or its Features,
                    however, it shall not be bound to effect the same unless satisfied of need to do so.
                </p>
                <p>Any update, upgrade and / or modification in the Product and / or its Features
                    during the period of Subscription shall be made available to you at no additional
                    fee, however, the Vendor may at its discretion offer the same (or part thereof) to
                    you at your option of purchase.
                </p>
                <p>The Vendor does not endorse, ratify or mandate availing of all, some or none of
                    the Features of the Product, and the same shall remain your personal choice.
                </p>
                <p>The Features of the Product can be deployed to create, modify or delete the same,
                    at your discretion and to your satisfaction.
                </p>
                <p>Services</p>
                <p>
                    The Vendor shall provide facilitating, ancillary and troubleshooting services
                    consequential to your Subscription of the Product, at no cost.
                </p>
                <p>The Vendor shall endeavour to provide such services promptly upon your raising
                    of such requirement, however, it shall not be bound to effect the same unless
                    satisfied of the need and / or its own resourcefulness to do so.
                </p>
                <p>The Vendor however does not permit services to be availed from any third
                    party(ies) towards the Product, without prior written consent of the Vendor.
                </p>
                <p>The Vendor also provides an optional Combo service of Share Digital Card with a
                    Website designed as per your requirements, bearing an endorsement of Vendor.
                </p>
                <p>The Vendor also provides an optional service of Google Advertisements, and you
                    may avail the same to your satisfaction, however, the results of which shall remain
                    subject to independent services by Google.
                </p>

                <h5><b>Use and conduct</b></h5>

                <p>
                    The Product warrants your responsible, prudent, and non-tortious conduct in its
                    Registration, Subscription and / or use.
                </p>
                <p>The Registration and Subscription of the Product creates a relationship of license
                    between the Vendor (being licensor) and you (being licensee) for you to Use the
                    same, limited by the Terms of Use.
                </p>
                <p>The license of the Product does not create any right, privilege or warranty in your
                    favour and over or against the Product or the Vendor.
                </p>
                <p>The license of the Product prohibits you from misusing and / or abusing the same
                    for any purpose that is or may become illegal in the eyes of law, against the public
                    policy and / or the Terms of Use.
                </p>


                <h5><b>Content</b></h5>

                <p>The content of the Account, Subscription and the Product is and shall remain the
                    Intellectual Property of the Vendor including but not limited to its Name,
                    Trademark(s), Copyright(s), Logo(s), Design(s), Patent(s), Source Code(s), Plans,
                    Features, layouts, themes, strategies, models, texts, images, videos, etc.
                </p>
                <p>The Subscription of the Product does not and shall not create, transfer or imply
                    any right over the Intellectual Property of the Vendor, in your favour to use,
                    misuse, abuse, share, plagiarize, reproduce, duplicate, sell or otherwise exploit the
                    same without prior written consent of the Vendor.
                </p>
                <p>The information received by you of and about the Product or the Vendor, through
                    Registration, Subscription or otherwise, including Intellectual Property of the
                    Vendor, shall be the Confidential Information of the Vendor, and you shall not
                    disclose, share or otherwise exploit the same without prior written consent of the
                    Vendor.
                </p>
                <p>It shall be your duty to promptly inform the Vendor about any infringement of
                    Intellectual Property Rights of the Vendor or any breach of confidentiality of its
                    Confidential Information at your behest or to your knowledge, and you shall
                    extend your cooperation to the Vendor in redressing the same by due process of
                    law.
                </p>
                <p>The Vendor does not claim any ownership over the Intellectual Property and
                    Confidential Information of its account-holders, subscribers and third party(ies),
                    and any such content uploaded upon the Product shall be governed by the <a href="privacy-policy.php">Privacy Policy</a>.

                </p>



                <h5><b>Renewal, Modification, Cancellation and Termination of Subscription</b></h5>

                <p>You may, during the period of Subscription or upon or after its expiry, and upon
                    duly informing the Vendor:
                    o Renew your Subscription by paying the Subscription Fee of Plan opted for
                    renewal;
                    o Modify your Subscription by paying the difference of Subscription Fee in case
                    of up-scaling of the Plan;
                    o Modify your Subscription by waiving off the difference of paid Subscription
                    Fee in case of down-scaling of the Plan; or,
                    o Cancel your Subscription by waiving off the Subscription Fee already paid.
                </p>
                <p>
                    The Vendor may, on just cause, at its sole discretion and upon duly informing
                    you, terminate your Subscription.
                </p>
                <p>In case of your Subscription having been expired, cancelled or terminated, your
                    Account, Product and all the consequential data may be retained at discretion of
                    the Vendor for a subsequent period of 7 days to facilitate its disposal at your end,
                    after which the same shall be deleted without issuing you any prior notice.
                </p>
                <p>The Vendor reserves its right to refuse renewal and modification of your
                    Subscription at its discretion.
                </p>
                <p>In the event of an inactive account for more than one month on the Free Plan, the system reserves the right to delete user data from the server due to account inactivity. Users will be required to register again within the system in order to create their digital card. This policy is in accordance with our terms of service and user agreement.</p>

                <h5><b>Deactivation and Deletion of Account</b></h5>
                <p>You may, during the period of Subscription or upon or after its expiry, and upon
                    duly informing the Vendor:
                <div class="p-left-20 dealer_icon">
                    <p>
                        <i class="fa fa-angle-right"></i> Deactivate your Account temporarily and then reactivate it; or,
                    </p>
                    <p><i class="fa fa-angle-right"></i> Delete your Account permanently and forfeit your Registration.</p>
                </div>
                <p>
                    The Vendor may, upon just cause, at its sole discretion and upon duly informing
                    you, temporarily deactivate or permanently delete your Account and effect
                    forfeiture of your Registration.
                </p>
                <p>In the event where you keep your Account deactivated for a continuous period of
                    1 year or if the same is deleted by you or the Vendor, your personal information
                    entered into the said Account shall be retained for a period of subsequent 7 days to
                    facilitate its disposal at your end, after which the same shall be deleted without
                    issuing you any prior notice.
                </p>
                <p>The Vendor reserves its right to refuse reactivation of your Account, and to refuse
                    Registration and creation of new Account after deletion of your Account, at its
                    discretion.

                </p>
                <h5><b>Discretion</b></h5>

                <p>The Vendor may, at its sole discretion, alter, remove, restrict, suspend or terminate
                    access, usage, feature and / or service of the Product, or may amend and enforce
                    amendment(s) of the Terms of Use as it may deem fit, without any prior notice to you;
                    and it shall be your responsibility to keep yourself conversant with the same to ensure
                    your pragmatic compliance of the Terms of Use.</p>
                <h5><b>Disclaimer</b></h5>

                <p>
                    The Vendor shall not be liable for any loss(es) caused due to your lack of
                    diligence, vigilance or prudence in Registration, Subscription and / or Use of the
                    Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to your lack of
                    accuracy, authenticity, correctness, validity and legality of information that you
                    enter for Registration, Subscription and / or Use of the Product.
                </p>
                <p>The Vendor shall not be responsible for removing, remedying or troubleshooting
                    unauthorized and / or unlawful use of your Account, Subscription and / or
                    Product, and shall not be liable for any loss(es) caused due to the same.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to disruption of
                    Registration, Subscription or Use of the Product owing to causes beyond its
                    control including but not limited to maintenance, power failure, server
                    malfunction, content loss, misuse or abuse, unwarranted access gained by hackers,
                    viruses or like infiltrators, force majeure, etc.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to human error and
                    error of belief, opinion or judgment.
                </p>
                <p>The Product provides Features for your availing by personal choice, and the
                    Vendor shall not be responsible for any loss(es) caused due to such availing of the
                    same.
                </p>
                <p>The Product may provide access to products / services for your availing, offered
                    by third party(ies) which are not under the control of Vendor, and the Vendor
                    shall not be liable for any loss(es) caused due to such access and availing of the
                    same.
                </p>
                <p>The Vendor shall likewise not be liable to any third party(ies) for any loss(es)
                    caused to such third party(ies) owing to any action or omission on your part
                    during, out of the course of, or in consequence of Registration, Subscription and /
                    or Use of the Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused to your equipment or
                    facilities utilized for Registration, Subscription and / or Use of the Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused as a consequence of any
                    action or omission at the behest of any person, entity or bot representing the
                    Vendor without due authorization from the Vendor.
                </p>
                <p>The Vendor shall not represent, ratify or defend you in any claim or complaint
                    made against you owing to any action or omission on your part during, out of the
                    course of, or in consequence of your Registration, Subscription or Use of the
                    Product; and / or in violation of the Terms of Use.
                </p>
                <h5><b>Liability and Indemnification</b></h5>

                <p>You shall solely be liable for, and shall indemnify, defend and hold the Vendor
                    harmless for any loss(es) caused to you, to any third party(ies), or to the Vendor; or
                    for any consequential loss(es); or for such loss(es) that may be saddled upon the
                    Vendor, owing to any action or omission on your part during, out of the course of, or
                    in consequence of your Registration, Subscription or Use of the Product; and / or in
                    violation of the Terms of Use.</p>
                <h5><b>Dispute Redressal</b></h5>

                <p>Any dispute arising out of or in connection with the Registration, Subscription or Use
                    of the Product; and / or in violation of the Terms of Use, shall be communicated by
                    the aggrieved party to the other party within three (3) days of occurrence of such
                    grievance, upon which the parties shall endeavour to resolve the same amicably
                    within subsequent 15 days, however, if such dispute is not so resolved, then either
                    party may initiate Arbitration proceedings for redressal of such dispute by serving the
                    other party with a Notice of 15 days to that effect, and the Vendor shall accordingly
                    appoint a sole Arbitrator to govern the Arbitral Tribunal at Mumbai, India, as per the
                    Indian Arbitration and Conciliation Act, 1996.

                </p>
                <h5><b>Governing Law and Jurisdiction</b></h5>

                <p>The Terms of Use, and the aforementioned process of dispute redressal shall be
                    governed by the laws prevailing in the Republic of India, being subject to the
                    jurisdiction for the purposes of enforcement, intervention and execution of the said
                    process vested in the Courts at Mumbai, India.
                </p>
                <h5><b>Contact:</b></h5>

                <p>The official contact information of the Vendor for all purposes shall be its Email Id –
                    <a href="mailto:info@sharedigitalcard.com">info@sharedigitalcard.com.</a>
                </p>
            </div>
        </div>
    </section>
@endsection
