@extends('layouts.web-main')
@section('main-container')
    <div class="innerpage-banner" id="home" style="background: url({{ url('/') }}/dist/assets/img/bread/breadcrumbs.jpg) no-repeat center; background-size: cover;">
        <div class="inner-page-layer">
            <h5>Terms And Conditions</h5>
            <h6><a href="{{ url('/') }}">Home</a>&nbsp;/&nbsp;<span>Terms And Conditions</span></h6>
        </div>
    </div>
    <section class="ptb--30" style="background: #f5f5f5">
        <div class="container">
            <div class="about-content terms_and_condition_content_point dealer_icon">
                <p>Share Digital Card Partnership Firm, Mumbai, the Vendor, offers you access to this
                    Website <a href="www.sharedigitalcard.com">www.sharedigitalcard.com</a>, which shall be governed by these
                    Terms and Conditions. The Vendor insists upon your prior perusal and understanding
                    of the same, and informs you that your access and / or use of the Website shall
                    automatically signify your consent to be bound by the Terms and Conditions, since
                    the same constitutes an electronic record defined under the laws prevailing in the
                    Republic of India, and having been generated by a computer system does not require
                    physical or personalized digital signatures for its authentication and enforcement.</p>
    
                <h5><b>Access, use and conduct</b></h5>
    
                <p><i class="fa fa-angle-right"></i> The Website is available for non-exclusive access on the World Wide Web, and
                    warrants your responsible, prudent, and non-tortious conduct in its use.</p>
                <p><i class="fa fa-angle-right"></i> The access and use of the Website creates a relationship of license between the
                    Vendor (being licensor) and you (being licensee) for you to use the same, limited
                    by the Terms and Conditions.</p>
                <p><i class="fa fa-angle-right"></i> The license does not create any right, privilege or warranty in your favour and
                    against the Website or the Vendor.</p>
                <p><i class="fa fa-angle-right"></i> The license prohibits you from misusing and / or abusing the same for any
                    purpose that is or may become illegal in the eyes of law, against the public policy
                    and / or the Terms and Conditions.</p>
    
                <h5><b>Content</b></h5>
    
                <p>The content of the Website is and shall remain the Intellectual Property of the
                    Vendor including but not limited to its Name, Domain, Link(s), Trademark(s),
                    Copyright(s), Logo(s), Design(s), Patent(s), Source Code(s), strategies, models,
                    texts, images, videos, etc.
                </p><p> The access and use of the Website does not and shall not create, transfer or imply
                    any right over the Intellectual Property of the Vendor, in your favour to use,
                    misuse, abuse, share, plagiarize, reproduce, duplicate, sell or otherwise exploit the
                    same without prior written consent of the Vendor.
                </p><p> It shall be your duty to promptly inform the Vendor about any infringement of
                    Intellectual Property Rights of the Vendor at your behest or to your knowledge,
                    and you shall extend your cooperation to the Vendor in redressing the same by
                    due process of law.
                </p><p> The Vendor does not claim any right over the Intellectual Property of its users,
                    subscribers and third party(ies), and any such content uploaded upon the Website
                    shall be governed by the <a href="privacy-policy.php">Privacy Policy</a>.
                </p>
    
                <h5><b>Discretion</b></h5>
    
                <p>The Vendor may, at its sole discretion, alter, remove, restrict, suspend or terminate
                    access, usage and / or content of the Website, or may amend and enforce
                    amendment(s) of the Terms and Conditions as it may deem fit, without any prior
                    notice to you; and it shall be your responsibility to keep yourself conversant with the
                    same to ensure your pragmatic compliance of the Terms and Conditions.</p>
    
                <h5><b>Disclaimer</b></h5>
    
                <p>The Vendor shall not be liable for any loss(es) caused due to your lack of
                    diligence, vigilance or prudence in access or use of the Website.
                </p><p> The Vendor shall not be liable for any loss(es) caused due to disruption of access,
                    use and services of the Website owing to causes beyond its control including but
                    not limited to maintenance, power failure, server malfunction, content loss,
                    misuse or abuse, unwarranted access gained by hackers, viruses or like infiltrators,
                    force majeure, etc.
                </p><p> The Vendor shall endeavour to not publish any incorrect, inaccurate or insensitive
                    content on the Website, however, it shall not be liable for any loss(es) caused by
                    such publication arising out of human error and error of belief, opinion or
                    judgment.
                </p><p> The Website may provide access to links offered by third party(ies) for their
                    destinations like websites, products and / or services which are not under the
                    control of the Vendor, and the Vendor shall not be liable for any loss(es) caused
                    due to such access and / or use of such links or of such destinations.
                </p><p> The Vendor shall likewise not be liable to any third party(ies) for any loss(es)
                    caused to such third party(ies) owing to any action or omission on your part
                    during, out of the course of, or in consequence of access or use of the Website.
                </p><p> The Vendor shall not be liable for any loss(es) caused to your equipment or
                    facilities utilized for access or use of the Website.
                </p><p> The Vendor shall not be liable for any loss(es) caused as a consequence of any
                    action or omission at the behest of any person, entity or bot representing the
                    Vendor or the Website without due authorization from the Vendor.
                </p><p> The Vendor shall not represent, ratify or defend you in any claim or complaint
                    made against you owing to any action or omission on your part during, out of the
                    course of, or in consequence of access or use of the Website; and / or in violation
                    of the Terms and Conditions.
                </p>
                <h5><b>Liability and Indemnification</b></h5>
                <p>You shall solely be liable for, and shall indemnify, defend and hold the Vendor
                    harmless for any loss(es) caused to you, to any third party(ies), or to the Vendor; or
                    for any consequential loss(es); or for such loss(es) that may be saddled upon the
                    Vendor, owing to any action or omission on your part during, out of the course of, or
                    in consequence of access or use of the Website; and / or in violation of the Terms and
                    Conditions.</p>
    
                <h5><b>Dispute Redressal</b></h5>
    
                <p>Any dispute arising out of or in connection with the access and / or use of the
                    Website; and / or in violation of the Terms and Conditions, shall be communicated by
                    the aggrieved party to the other party within three (3) days of occurrence of such
                    grievance, upon which the parties shall endeavour to resolve the same amicably
                    within subsequent 15 days, however, if such dispute is not so resolved, then either
                    party may initiate Arbitration proceedings for redressal of such dispute by serving the
                    other party with a Notice of 15 days to that effect, and the Vendor shall accordingly
                    appoint a sole Arbitrator to govern the Arbitral Tribunal at Mumbai, India, as per the
                    Indian Arbitration and Conciliation Act, 1996.
                </p>
                <h5><b>Governing Law and Jurisdiction</b></h5>
    
                <p>The Terms and Conditions, and the aforementioned process of dispute redressal shall
                    be governed by the laws prevailing in the Republic of India, being subject to the
                    jurisdiction for the purposes of enforcement, intervention and execution of the said
                    process vested in the Courts at Mumbai, India.</p>
                <h5><b>Contact</b></h5>
    
                <p>The official contact information of the Vendor for all purposes shall be its Email Id –
                    <a href="mailto:info@sharedigitalcard.com">info@sharedigitalcard.com.</a></p>
    
            </div>
        </div>
    </section>
    
@endsection
