@extends('layouts.web-main')
@section('main-container')
    <div class="innerpage-banner" id="home" style="background: url({{ url('/') }}/dist/assets/img/bread/breadcrumbs.jpg) no-repeat center; background-size: cover;">
        <div class="inner-page-layer">
            <h5>Terms of Dealership</h5>
            <h6><a href="{{url('/')}}">Home</a>&nbsp;/&nbsp;<span>Terms of Dealership</span></h6>
        </div>
    </div>
    <section class="ptb--30" style="background: #f5f5f5">
        <div class="container">
            <div class="about-content terms_and_condition_content_point dealer_icon">
                <p>
                    Share Digital Card, a digital business card is a Product created, owned and distributed
                    by Share Digital Card Partnership Firm, Mumbai, the Vendor through its Website
                    <a href="www.sharedigitalcard.com">www.sharedigitalcard.com</a>. The Vendor offers a Dealership Program which shall be governed by these Terms of Dealership. Any transaction
                    arising out of or being consequential to these Terms of Dealership shall also be bound
                    by the Terms and Conditions, Terms of Use and Privacy Policy published on this
                    Website. The Vendor insists upon your prior perusal and understanding of the same,
                    and informs you that your access or use of the Website shall automatically signify
                    your consent to be bound by the Terms and Conditions, Terms of Use, Privacy Policy
                    and Terms of Dealership, since the same constitute an electronic record defined under
                    the laws prevailing in the Republic of India, and having been generated by a computer
                    system does not require physical or personalized digital signatures for its
                    authentication and enforcement.

                </p>

                <h5><b>Dealer Registration</b></h5>

                <p>The Dealership Program can be availed by registering as a Dealer upon creating a
                    Dealer Account on the Website by setting up your personal information including
                    your name, Email Id, physical address, phone number, Login Id and password,
                    and upon complying with the primary contact-verification process.
                </p>
                <p>You shall be required to provide original and valid documents with respect to your
                    identification, and it shall be deemed to have been undertaken by you that the
                    information provided, belongs to you and is not false, fraudulent or illegal.
                </p>
                <p>It shall solely be your responsibility to protect your Account credentials, and any
                    use, misuse or abuse of your the same shall be attributable to you.
                </p>
                <p>In the event where any unauthorised access or operation of your Account comes to
                    your knowledge, you shall promptly report the same to the Vendor.
                </p>
                <p>The Account shall be operated only by the person whose personal information has
                    been entered in the same.
                </p>
                <p>The Vendor reserves its right to refuse your Registration and creation of your
                    Account, at its discretion.
                </p>

                <h5><b>Dealer Subscription</b></h5>

                <p> The Dealership Program can be availed by subscribing to the shared plan via email. </p>
                <!--   <div class="p-left-20 dealer_icon">
                        <p><i class="fa fa-angle-right"></i>  Free Trial: For a period of five (5) days from the date of Registration for the
                            first time, at no cost.
                        </p><p><i class="fa fa-angle-right"></i>  Annual: For a period of one (1) year from the date of Subscription, at a
                            Subscription Fee of Rs. 999/-.
                        </p><p><i class="fa fa-angle-right"></i>  Triennial: For a period of three (3) years from the date of Subscription, at a
                            Subscription Fee of Rs. 1,999/-.
                        </p><p><i class="fa fa-angle-right"></i>  Quinquennial: For a period of five (5) years from the date of Subscription, at a
                            Subscription Fee of Rs. 2,999/-.
                        </p><p><i class="fa fa-angle-right"></i>  Lifetime: For your lifetime from the date of Subscription, at a Subscription
                            Fee of Rs. 4,999/-.
                        </p>
        
                    </div>-->
                <p>The Subscription Fee of opted Plan shall be payable by you at the beginning of
                    Subscription or (in case of) modification / renewal through either of the modes or
                    payment prescribed by the Vendor from time to time.
                </p>
                <p>
                    Subscription plan validity will be as per the shared plan details via email.
                </p>
                <p>The Subscription Fee of opted Plan shall be payable by you at the beginning of
                    Subscription or (in case of) modification through either of the modes or payment
                    prescribed by the Vendor from time to time.
                </p>
                <p>The Subscription once opted shall be non-transferrable and the Subscription Fee
                    once paid shall be non-refundable, under any circumstances.
                </p>
                <p>The Vendor reserves its right to change the Subscription Fee at any point of time
                    without issuing any prior notice, however, such change shall not affect the
                    existing Subscription (if any) until its expiry.
                </p>
                <p>The Subscription shall be considered valid only through your compliance of the
                    Indian Contract Act, 1872, including your competence in terms of majority of age,
                    soundness of mind, solvency and legality of your Registration, Subscription and /
                    or Dealership of the Product.
                </p>
                <p>The Subscription shall not survive through and beyond suspension, winding up or
                    dissolution of the Vendor, and / or discontinuation of the Product.
                </p>
                <p>The Vendor reserves its right to refuse your Subscription, at its discretion.
                </p>


                <h5><b>Role of Vendor</b></h5>

                <p>The Vendor shall provide you the requisite training and material for effecting
                    Dealership of the Product.
                </p>
                <p>The Vendor shall provide requisite support to the Vendee(s) approaching the
                    Vendor through your Account.

                </p>
                <p>Role of Dealer</p>
                <p>You shall diligently receive training and material from and to the satisfaction of
                    the Vendor.
                </p>
                <p>You shall formulate marketing and sales strategies with and to the satisfaction of
                    the Vendor.
                </p>
                <p>You shall pitch the Product as directed and authorised by the Vendor.
                </p>
                <p>You shall promptly intimate the Vendor of prospective Vendee(s) seeking to avail
                    the Product.
                </p>
                <p>You shall aid and assist the Vendor in delivering, demonstrating and designing the
                    Product to such Vendee(s).
                </p>
                <p>You shall, if so required and directed by the Vendor, either through itself and / or
                    through such person(s) authorised and deployed by the Vendor and / or any such
                    Third Party approved by the Vendor, aid and assist the Vendor in providing
                    servicing and maintenance towards the Product to the Vendee(s).
                </p>
                <p>You shall, in the event of requirement to address any dispute with the Vendee(s)
                    and upon receiving such direction and authorisation from the Vendor, attend to
                    such dispute in the form and manner as prescribed by the Vendor, at the relevant
                    time.
                </p>
                <p>You shall, on a monthly basis or otherwise as and when required by the Vendor,
                    submit Report(s) of the progress in Dealership Program.
                </p>
                <p>You shall make commitments to the Vendee(s) only in consultation with the
                    Vendor and in any case, through Email(s) keeping the Vendor in CC.
                </p>
                <p>You may represent the Vendor or identify itself, only during the Term of
                    Subscription, in the capacity of an independent and non-exclusive Dealer of the
                    Vendor.
                </p>
                <p>You shall return each tangible material of the Vendor and / or provided by the
                    Vendor, to the Vendor upon termination of your Subscription.
                </p>
                <p>You shall destroy or otherwise dispose off, only as and when directed by the
                    Vendor, any material and / or information of the Vendor and / or provided by the
                    Vendor, and shall provide proof of the same as may be required by the Vendor.
                </p>
                <p>You may be granted access to the information of the Vendee(s) approaching the
                    Vendor through the referral from your Account, however, in any case except
                    banking information of such Vendee(s).
                </p>
                <p>You shall, at all times, be in compliance of all the laws of the Republic of India
                    prevailing at the relevant time.

                </p>

                <h5><b>Restrictions</b></h5>

                <p>The Dealership Program warrants your responsible, prudent, and non-tortious
                    conduct in its Registration, Subscription and / or Dealership.
                </p>
                <p>The Dealership Program creates a relationship of license between the Vendor
                    (being licensor) and you the Dealer (being licensee) to effect the same, limited by
                    the Terms of Dealership.
                </p>
                <p>The license of the Product does not create any right, privilege or warranty in your
                    favour and over or against the Product or the Vendor.
                </p>
                <p>You shall not misuse and / or abuse the same or the Product or the representation
                    of Vendor for any purpose that is or may become illegal in the eyes of law, against
                    the public policy and / or the Terms of Dealership.
                </p>
                <p>You shall not indulge into any act or omission in violation of, or may cause the
                    Vendor or Vendee to violate, the law prevailing at the relevant time in the
                    Republic of India, the public policy and / or Terms of Dealership.
                </p>
                <p>You shall not indulge into any act or omission without due authorization from the
                    Vendor.
                </p>
                <p>You shall not indulge into any act or omission that may oust or cause assumption
                    to have ousted the authority of the Vendor to govern the Product, the Dealership
                    Program and the consequences running therefrom.
                </p>
                <p>You shall not indulge into any act or omission that may besmirch the goodwill and
                    reputation of the Vendor.
                </p>
                <p>You shall not indulge into any act or omission that may cause loss / delay of
                    business to the Vendor.
                </p>
                <p>You shall not indulge into any act or omission that may cause imposition of any
                    legal liability upon the Vendor.
                </p>
                <p>You shall not indulge into any act or omission that may occasion any overcommitment, promise or understanding on behalf of the Vendor, unless so
                    directed and authorized by the Vendor.
                </p>
                <p>You shall not assume any right, privilege or liberty that is not explicitly granted
                    by the Vendor.
                </p>
                <p>You shall not transfer, assign or sublet any right, privilege or liberty granted
                    Vendor, to any person and / or entity.
                </p>
                <p>You shall not indulge into any act or omission that is or may lead to be in conflict
                    with its interest towards the Vendor and / or with interests of the Vendor.
                </p>
                <p>You shall not compete and / or cause competition with interests of the Vendor, in
                    any manner whatsoever, during the Term of Subscription and for a period of 5 years beyond its termination.
                </p>
                <p>You shall not indulge into any act or omission that may solicit, harass or cause
                    any loss, damage or injury to, any person / entity concerned with the Vendor.
                </p>
                <p>You shall not, unless otherwise required by the Vendor, obliterate, deviate from,
                    and / or cease to honour the Terms of Dealership.
                </p>
                <p>You shall not sell the Product over the Market Price as fixed by the Vendor from
                    time to time, however, you may, at your discretion however with precaution as to
                    not cause any loss to the Product or the Vendor, add data / design services upon
                    the Product and sell the same to the Vendee(s) to their satisfaction.
                </p>
                <p>You shall not be an employee or in any case an agent of the Vendor, and you shall
                    not represent the Vendor in any such manner, under any circumstances
                    whatsoever.

                </p>


                <h5><b>Content</b></h5>

                <p>The content of the Account, Subscription and the Product is and shall remain the
                    Intellectual Property of the Vendor including but not limited to its Name,
                    Trademark(s), Copyright(s), Logo(s), Design(s), Patent(s), Source Code(s), Plans,
                    Features, layouts, themes, strategies, models, texts, images, videos, etc.
                </p>
                <p>The Subscription of the Product does not and shall not create, transfer or imply
                    any right over the Intellectual Property of the Vendor, in your favour to use,
                    misuse, abuse, share, plagiarize, reproduce, duplicate, sell or otherwise exploit the
                    same without prior written consent of the Vendor.
                </p>
                <p>The information received by you of and about the Product or the Vendor, through
                    Registration, Subscription or otherwise, including Intellectual Property of the
                    Vendor, shall be the Confidential Information of the Vendor, and you shall not
                    disclose, share or otherwise exploit the same without prior written consent of the
                    Vendor.
                </p>
                <p>It shall be your duty to promptly inform the Vendor about any infringement of
                    Intellectual Property Rights of the Vendor or any breach of confidentiality of its
                    Confidential Information at your behest or to your knowledge, and you shall
                    extend your cooperation to the Vendor in redressing the same by due process of
                    law.
                </p>
                <p>The Vendor does not claim any ownership over the Intellectual Property and
                    Confidential Information of its account-holders, subscribers and third party(ies),
                    and any such content uploaded upon the Product shall be governed by the <a href="privacy-policy.php">Privacy Policy</a>.</p>



                <h5><b>Renewal, Modification, Cancellation and Termination of Dealer Subscription</b></h5>

                <p>You may, during the period of Subscription or upon or after its expiry, and upon
                    duly informing the Vendor:
                    o Renew your Subscription by paying the Subscription Fee of Plan opted for
                    renewal;
                    o Modify your Subscription by paying the difference of Subscription Fee in case
                    of up-scaling of the Plan (only within 2 months from the date of Subscription);
                    o Modify your Subscription by waiving off the difference of paid Subscription
                    Fee in case of down-scaling of the Plan; or,
                    o Cancel your Subscription by waiving off the Subscription Fee already paid.
                </p>
                <p>The Vendor may, on just cause, at its sole discretion and upon duly informing
                    you, terminate your Subscription.
                </p>
                <p>In case of your Subscription having been expired, cancelled or terminated, the
                    Product shall become available to you at Market Price; and your Account and all
                    the consequential data may be retained at discretion of the Vendor for a
                    subsequent period of 7 days to facilitate its disposal at your end, after which the
                    same shall be deleted without issuing you any prior notice.
                </p>
                <p>The Vendor reserves its right to refuse renewal and modification of your
                    Subscription at its discretion.

                </p>

                <h5><b>Deactivation and Deletion of Account</b></h5>
                <p>The Dealer may, during the period of Subscription or upon or after its expiry, and
                    upon duly informing the Vendor:
                <div class="p-left-20 dealer_icon">
                    <p>
                        <i class="fa fa-angle-right"></i> Deactivate Account temporarily and then reactivate it; or,
                    </p>
                    <p><i class="fa fa-angle-right"></i> Delete Account permanently and forfeit the Registration</p>
                </div>
                <p>The Vendor may, upon just cause, at its sole discretion and upon duly informing
                    you, temporarily deactivate or permanently delete your Account and effect
                    forfeiture of your Registration.
                </p>
                <p>In the event where the you keep your Account deactivated for a continuous period
                    of 1 year or if the same is deleted, the personal information entered into the said
                    Account shall be retained for a period of subsequent 7 days to facilitate its
                    disposal at your end, after which the same shall be deleted without issuing you
                    any prior notice.
                </p>
                <p>The Vendor reserves its right to refuse reactivation of your Account, and to refuse
                    Registration and creation of new Account after deletion of your Account, at its
                    discretion.
                </p>
                <h5><b>Exclusivity over Vendee(s)</b></h5>

                <p>During, through and beyond the Term of Dealership Program, your Subscription and /
                    or your Account, regardless of its / their cessation for any reason whatsoever (if any),
                    the Vendee(s) approaching the Vendor through the referral from your Dealer Account,
                    whether in the prevailing situation or in the future, shall remain exclusive to the
                    Vendor, and you shall not exercise and right, authority or restriction over such
                    Vendee(s).</p>

                <h5><b>Discretion</b></h5>

                <p>The Vendor may, at its sole discretion, alter, remove, restrict, suspend or terminate
                    access, usage, feature and / or service of the Dealership Program or of the Product, or
                    may amend and enforce amendment(s) of the Terms of Dealership as it may deem fit,
                    without any prior notice; and it shall be your responsibility to keep yourself
                    conversant with the same to ensure your pragmatic compliance of the Terms of
                    Dealership.</p>

                <h5><b>Disclaimer</b></h5>

                <p>The Vendor shall not be liable for any loss(es) caused due to your lack of
                    diligence, vigilance or prudence in Registration, Subscription and / or Dealership
                    of the Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to your lack of
                    accuracy, authenticity, correctness, validity and legality of information that you
                    enter for Registration, Subscription and / or Dealership of the Product.
                </p>
                <p>The Vendor shall not be responsible for removing, remedying or troubleshooting
                    unauthorized and / or unlawful use of your Account, Subscription and / or
                    Dealership of the Product, and shall not be liable for any loss(es) caused due to the
                    same.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to disruption of
                    Registration, Subscription or Dealership of the Product owing to causes beyond its
                    control including but not limited to maintenance, power failure, server
                    malfunction, content loss, misuse or abuse, unwarranted access gained by hackers,
                    viruses or like infiltrators, force majeure, etc.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused due to human error and
                    error of belief, opinion or judgment.
                </p>
                <p>The Product provides Features for availing of the Vendee(s) by personal choice,
                    and the Vendor shall not be responsible for any loss(es) caused due to such
                    availing of the same.
                </p>
                <p>The Product may provide access to products / services for availing of the
                    Vendee(s), offered by third party(ies) which are not under the control of Vendor,
                    and the Vendor shall not be liable for any loss(es) caused due to such access and
                    availing of the same.
                </p>
                <p>The Vendor shall likewise not be liable to any of your Vendee(s) for any loss(es)
                    caused to such Vendee(s) owing to any action or omission on your part during, out
                    of the course of, or in consequence of Registration, Subscription and / or
                    Dealership of the Product.
                </p>
                <p>The Vendor shall also not be liable to any third party(ies) for any loss(es) caused
                    to such third party(ies) owing to any action or omission on your part during, out of
                    the course of, or in consequence of Registration, Subscription and / or Dealership
                    of the Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused to your equipment or
                    facilities utilized for Registration, Subscription and / or Dealership of the Product.
                </p>
                <p>The Vendor shall not be liable for any loss(es) caused as a consequence of any
                    action or omission at the behest of any person, entity or bot representing the
                    Vendor without due authorization from the Vendor.
                </p>
                <p>The Vendor shall not represent, ratify or defend you in any claim or complaint
                    made against you owing to any action or omission on your part during, out of the
                    course of, or in consequence of your Registration, Subscription or Dealership of
                    the Product; and / or in violation of the Terms of Dealership.

                </p>
                <h5><b>Liability and Indemnification</b></h5>

                <p>You shall solely be liable for, and shall indemnify, defend and hold the Vendor
                    harmless for any loss(es) caused to you, to any third party(ies), or to the Vendor; or
                    for any consequential loss(es); or for such loss(es) that may be saddled upon the
                    Vendor, owing to any action or omission on your part during, out of the course of, or
                    in consequence of your Registration, Subscription or Dealership of the Product; and /
                    or in violation of the Terms of Dealership.
                </p>
                <h5><b>Dispute Redressal</b></h5>

                <p>Any dispute arising out of or in connection with the Registration, Subscription or
                    Dealership of the Product; and / or in violation of the Terms of Dealership, shall be
                    communicated by the aggrieved party to the other party within three (3) days of
                    occurrence of such grievance, upon which the parties shall endeavour to resolve the
                    same amicably within subsequent 15 days, however, if such dispute is not so resolved,
                    then either party may initiate Arbitration proceedings for redressal of such dispute by
                    serving the other party with a Notice of 15 days to that effect, and the Vendor shall
                    accordingly appoint a sole Arbitrator to govern the Arbitral Tribunal at Mumbai,
                    India, as per the Indian Arbitration and Conciliation Act, 1996.

                </p>
                <h5><b>Governing Law and Jurisdiction</b></h5>

                <p>The Terms of Dealership, and the aforementioned process of dispute redressal shall be
                    governed by the laws prevailing in the Republic of India, being subject to the
                    jurisdiction for the purposes of enforcement, intervention and execution of the said
                    process vested in the Courts at Mumbai, India.
                </p>
                <h5><b>Contact:</b></h5>

                <p>The official contact information of the Vendor for all purposes shall be its Email Id –
                    <a href="mailto:support@sharedigitalcard.com">support@sharedigitalcard.com.</a>
                </p>
            </div>
        </div>
    </section>
@endsection
